/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as LoginRouteImport } from './app/login'
import { Route as AuthenticatedRouteImport } from './app/_authenticated'
import { Route as IndexRouteImport } from './app/index'
import { Route as AuthenticatedSourcesRouteImport } from './app/_authenticated.sources'
import { Route as AuthenticatedDashboardRouteImport } from './app/_authenticated.dashboard'
import { Route as AuthenticatedArticlesRouteImport } from './app/_authenticated.articles'
import { Route as ApiSessionRefreshRouteImport } from './app/api.session.refresh'
import { Route as AuthenticatedSourcesIdRouteImport } from './app/_authenticated.sources.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSourcesRoute = AuthenticatedSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArticlesRoute = AuthenticatedArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiSessionRefreshRoute = ApiSessionRefreshRouteImport.update({
  id: '/api/session/refresh',
  path: '/api/session/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSourcesIdRoute = AuthenticatedSourcesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/articles': typeof AuthenticatedArticlesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/sources': typeof AuthenticatedSourcesRouteWithChildren
  '/sources/$id': typeof AuthenticatedSourcesIdRoute
  '/api/session/refresh': typeof ApiSessionRefreshRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/articles': typeof AuthenticatedArticlesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/sources': typeof AuthenticatedSourcesRouteWithChildren
  '/sources/$id': typeof AuthenticatedSourcesIdRoute
  '/api/session/refresh': typeof ApiSessionRefreshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/articles': typeof AuthenticatedArticlesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/sources': typeof AuthenticatedSourcesRouteWithChildren
  '/_authenticated/sources/$id': typeof AuthenticatedSourcesIdRoute
  '/api/session/refresh': typeof ApiSessionRefreshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/articles'
    | '/dashboard'
    | '/sources'
    | '/sources/$id'
    | '/api/session/refresh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/articles'
    | '/dashboard'
    | '/sources'
    | '/sources/$id'
    | '/api/session/refresh'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/articles'
    | '/_authenticated/dashboard'
    | '/_authenticated/sources'
    | '/_authenticated/sources/$id'
    | '/api/session/refresh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiSessionRefreshRoute: typeof ApiSessionRefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sources': {
      id: '/_authenticated/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AuthenticatedSourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/articles': {
      id: '/_authenticated/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof AuthenticatedArticlesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/session/refresh': {
      id: '/api/session/refresh'
      path: '/api/session/refresh'
      fullPath: '/api/session/refresh'
      preLoaderRoute: typeof ApiSessionRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sources/$id': {
      id: '/_authenticated/sources/$id'
      path: '/$id'
      fullPath: '/sources/$id'
      preLoaderRoute: typeof AuthenticatedSourcesIdRouteImport
      parentRoute: typeof AuthenticatedSourcesRoute
    }
  }
}

interface AuthenticatedSourcesRouteChildren {
  AuthenticatedSourcesIdRoute: typeof AuthenticatedSourcesIdRoute
}

const AuthenticatedSourcesRouteChildren: AuthenticatedSourcesRouteChildren = {
  AuthenticatedSourcesIdRoute: AuthenticatedSourcesIdRoute,
}

const AuthenticatedSourcesRouteWithChildren =
  AuthenticatedSourcesRoute._addFileChildren(AuthenticatedSourcesRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedArticlesRoute: typeof AuthenticatedArticlesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSourcesRoute: typeof AuthenticatedSourcesRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedArticlesRoute: AuthenticatedArticlesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSourcesRoute: AuthenticatedSourcesRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiSessionRefreshRoute: ApiSessionRefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
